#ifndef GUARD_CONSTANTS_BATTLE_MOVE_RESOLUTION_H
#define GUARD_CONSTANTS_BATTLE_MOVE_RESOLUTION_H

enum Obedience
{
    OBEYS,
    DISOBEYS_LOAFS,
    DISOBEYS_HITS_SELF,
    DISOBEYS_FALL_ASLEEP,
    DISOBEYS_WHILE_ASLEEP,
    DISOBEYS_RANDOM_MOVE,
};

enum CancelerResult
{
    CANCELER_RESULT_SUCCESS,
    CANCELER_RESULT_RUN_SCRIPT_AND_INCREMENT, // Runs script. Increments state
    CANCELER_RESULT_RUN_SCRIPT, // Runs script. Does not increment state
    CANCELER_RESULT_FAILURE, // Move failed, jump to script that handles the failure
    CANCELER_RESULT_END, // prevents going into canceler again
};

enum TargetFailure
{
    TARGET_FAILURE_SEMI_INVULNERABILITY,
    TARGET_FAILURE_PSYCHIC_TERRAIN,
    TARGET_FAILURE_PROTECT,
    TARGET_FAILURE_BOUNCE,
    TARGET_FAILURE_TARGET_BLOCKED,
    TARGET_FAILURE_EFFECTIVENESS,
};

enum PreAnimActivations
{
    PRE_ANIM_STRONG_WINDS,
    PRE_ANIM_TERA_SHELL,
    PRE_ANIM_RESIST_BERRY,
};

enum CancelerState
{
    CANCELER_STANCE_CHANGE_1,
    CANCELER_CLEAR_FLAGS,
    CANCELER_SKY_DROP,
    CANCELER_RECHARGE,
    CANCELER_CHILLY_RECEPTION,
    CANCELER_ASLEEP_OR_FROZEN,
    CANCELER_POWER_POINTS,
    CANCELER_OBEDIENCE,
    CANCELER_TRUANT,
    CANCELER_FOCUS_GEN5,
    CANCELER_FLINCH,
    CANCELER_DISABLED,
    CANCELER_VOLATILE_BLOCKED, // Gravity / Heal Block / Throat Chop
    CANCELER_TAUNTED,
    CANCELER_IMPRISONED,
    CANCELER_CONFUSED,
    CANCELER_GHOST,
    CANCELER_PARALYZED,
    CANCELER_INFATUATION,
    CANCELER_Z_MOVES,
    CANCELER_CHOICE_LOCK,
    CANCELER_CALLSUBMOVE,
    CANCELER_THAW,
    CANCELER_STANCE_CHANGE_2,
    CANCELER_ATTACKSTRING,
    CANCELER_PLEDGE_ATTACK,
    CANCELER_SET_TARGETS,
    CANCELER_PPDEDUCTION,
    CANCELER_MOVE_SPECIFIC_MESSAGE,
    CANCELER_SKY_BATTLE,
    CANCELER_WEATHER_PRIMAL,
    CANCELER_FOCUS_PRE_GEN5,
    CANCELER_BIDE,
    CANCELER_MOVE_FAILURE,
    CANCELER_MOVE_EFFECT_FAILURE_TARGET,
    CANCELER_POWDER_STATUS,
    CANCELER_PRIORITY_BLOCK,
    CANCELER_EXPLODING_DAMP,
    CANCELER_INTERRUPTIBLE_MOVES,
    CANCELER_PROTEAN,
    CANCELER_CHARGING,
    CANCELER_SNATCH,
    CANCELER_EXPLOSION,
    CANCELER_NO_TARGET,
    CANCELER_TOOK_ATTACK,
    CANCELER_TARGET_FAILURE,
    CANCELER_MULTIHIT_MOVES,
    CANCELER_SUBSTITUTE,
    CANCELER_ACCURACY_CHECK,
    CANCELER_PRE_ATTACK_MOVE_EFFECT,
    CANCELER_DAMAGE_CALC,
    CANCELER_PRE_ANIM_ACTIVATIONS,
    CANCELER_MOVE_ANIMATION,
    CANCELER_EFFECTIVENESS_SOUND,
    CANCELER_HIT_ANIMATION,
    CANCELER_SKIP_FRAME,
    CANCELER_HEALTH_BAR_UPDATE,
    CANCELER_MOVE_DAMAGE_UPDATE,
    CANCELER_END,
};

enum MoveEndResult
{
    MOVEEND_RESULT_CONTINUE,
    MOVEEND_RESULT_RUN_SCRIPT,
    MOVEEND_RESULT_BREAK,
};

// cases for MOVEEND_SUBSTITUTE_BLOCK
enum SubstituteBlockStates
{
    SUBSTITUTE_BLOCK_EFFECTIVENESS_MESSAGE,
    SUBSTITUTE_BLOCK_CRIT_MESSAGE,
    SUBSTITUTE_BLOCK_BYPASS_PROTECT_MESSAGE,
    SUBSTITUTE_BLOCK_DAMAGED_MESSAGE,
    SUBSTITUTE_BLOCK_SUBSTITUTE_DISAPPEARS,
    SUBSTITUTE_BLOCK_ADDITIONAL_EFFECTS,
    SUBSTITUTE_BLOCK_ITEM_EFFECT_TARGET,
    SUBSTITUTE_BLOCK_PROTECT_LIKE_EFFECT,
    // SUBSTITUTE_BLOCK_DYNAMAX_MOVE_EFFECTS,
    SUBSTITUTE_BLOCK_COUNT,
};

// cases for MOVEEND_DAMAGED_EFFECTS_BLOCK
enum DamagedEffectsBlockStates
{
    // DAMAGED_EFFECTS_BLOCK_CORE_ENFORCER,
    DAMAGED_EFFECTS_BLOCK_RAGE,
    // DAMAGED_EFFECTS_BLOCK_CLEAR_SMOG,
    DAMAGED_EFFECTS_BLOCK_GRUDGE,
    DAMAGED_EFFECTS_BLOCK_BEAK_BLAST,
    DAMAGED_EFFECTS_BLOCK_ATTACKER_ABILITY, // ABILITYEFFECT_MOVE_END_ATTACKER
    DAMAGED_EFFECTS_BLOCK_TARGET_ABILITY, // ABILITYEFFECT_MOVE_END
    DAMAGED_EFFECTS_BLOCK_RESIST_BERRY_MESSAGE,
    DAMAGED_EFFECTS_BLOCK_ITEM_EFFECTS_TARGET, // Enigma Berry, Weakness Policy, Snowball and similar items, Rocky Helmet, Sticky Barb, Air Balloon
    // DAMAGED_EFFECTS_BLOCK_INCINERATE,
    DAMAGED_EFFECTS_BLOCK_ITEM_EFFECTS_ATTACKER, // King's Rock
    DAMAGED_EFFECTS_BLOCK_JABOCA_ROWAP,
    DAMAGED_EFFECTS_BLOCK_FORM_CHANGE_AFTER_HIT, // Message, form change and Disguise damage
    DAMAGED_EFFECTS_BLOCK_PROTECT_LIKE_EFFECTS,
    DAMAGED_EFFECTS_BLOCK_COUNT,
};

// cases for MOVEEND_FAINT_BLOCK
enum FaintBlockStates
{
    FAINT_BLOCK_FINAL_GAMBIT,
    FAINT_BLOCK_CHECK_TARGET_FAINTED, // Exits if target is not fainted
    FAINT_BLOCK_VICTORY_CATCH,
    FAINT_BLOCK_END_NEUTRALIZING_GAS,
    // Destiny Bond is tested and called first, but Faint Target's script plays first
    FAINT_BLOCK_TRY_DESTINY_BOND,
    FAINT_BLOCK_FAINT_TARGET,
    FAINT_BLOCK_COUNT,
};

// cases for MOVEEND_MULTIHIT_BLOCK
enum MultihitBlockStates
{
    MULTIHIT_BLOCK_HP_THRESHOLD_ITEMS,
    MULTIHIT_BLOCK_DECREMENT_HIT,
    MULTIHIT_BLOCK_SMART_REDIRECTION,
    MULTIHIT_BLOCK_INTERRUPT_EXECUTION,
    MULTIHIT_BLOCK_EFFECTIVENESS_MESSAGE,
    MULTIHIT_BLOCK_NEXT_HIT,
    MULTIHIT_BLOCK_PRINT_NUM_OF_HITS,
    MULTIHIT_BLOCK_COUNT,
};

// cases for Cmd_moveend - Order matters!
enum MoveEndState
{
    MOVEEND_SET_VALUES,
    MOVEEND_QUEUE_DANCER_TOXIC_CHAIN,
    // User's side
    MOVEEND_SUBSTITUTE_BLOCK_ALLIED_SIDE,
    MOVEEND_MOVE_HEAVY_RECOIL, // Explosion, Steel Beam and similar moves
    MOVEEND_EFFECTIVENESS_MESSAGE_ALLIED_SIDE, // Multi-target and single-target
    MOVEEND_CRIT_PROTECT_MESSAGE_ALLIED_SIDE, // Crit message, then target couldn't protect itself for each target
    MOVEEND_ENDURE_DAMAGE_MESSAGE_ALLIED_SIDE, // Endure, False Swipe/Hold Back, Sturdy, Focus Sash/Focus Band, Friendship, in that order
    MOVEEND_PROTECT_LIKE_EFFECTS_ALLIED_SIDE,
    MOVEEND_ADDITIONAL_EFFECTS_ALLIED_SIDE,
    MOVEEND_ABSORB_ALLIED_SIDE,
    MOVEEND_STATUS_IMMUNITY_ABILITIES_ALLIED_SIDE, // TODO: Do berries come before????
    MOVEEND_ATTACKER_INVISIBLE,
    MOVEEND_ATTACKER_VISIBLE,
    MOVEEND_TARGET_VISIBLE_ALLIED_SIDE,
    MOVEEND_DAMAGED_EFFECTS_BLOCK_ALLIED_SIDE,
    MOVEEND_ILLUSION_ENDS_ALLIED_SIDE,
    MOVEEND_MENTAL_HERB_ALLIED_SIDE,
    MOVEEND_SYMBIOSIS_ALLIED_SIDE,
    MOVEEND_FAINT_BLOCK_ALLIED_SIDE,
    MOVEEND_FAINT_ATTACKER_ALLIED_SIDE,
    MOVEEND_UPDATE_LAST_MOVES_ALLIED_SIDE,
    MOVEEND_MIRROR_MOVE_ALLIED_SIDE,
    // Switch to opposing side
    MOVEEND_SET_VALUES_FOR_OPPOSING_SIDE,
    MOVEEND_SUBSTITUTE_BLOCK_OPPOSING_SIDE,
    MOVEEND_EFFECTIVENESS_MESSAGE_OPPOSING_SIDE, // Multi-target and single-target
    MOVEEND_CRIT_PROTECT_MESSAGE_OPPOSING_SIDE, // Crit message, then target couldn't protect itself for each target
    MOVEEND_ENDURE_DAMAGE_MESSAGE_OPPOSING_SIDE, // Endure, False Swipe/Hold Back, Sturdy, Focus Sash/Focus Band, Friendship, in that order
    MOVEEND_PROTECT_LIKE_EFFECTS_OPPOSING_SIDE,
    MOVEEND_ADDITIONAL_EFFECTS_OPPOSING_SIDE,
    MOVEEND_ADDITIONAL_EFFECTS_LOWER_STATS_ATTACKER,
    MOVEEND_ABSORB_OPPOSING_SIDE,
    MOVEEND_STATUS_IMMUNITY_ABILITIES_OPPOSING_SIDE, // TODO: Do berries come before????
    MOVEEND_TARGET_VISIBLE_OPPOSING_SIDE,
    MOVEEND_DAMAGED_EFFECTS_BLOCK_OPPOSING_SIDE,
    MOVEEND_ILLUSION_ENDS_OPPOSING_SIDE,
    MOVEEND_MENTAL_HERB_OPPOSING_SIDE,
    MOVEEND_SYMBIOSIS_OPPOSING_SIDE,
    MOVEEND_FAINT_BLOCK_OPPOSING_SIDE,
    MOVEEND_FAINT_ATTACKER_OPPOSING_SIDE,
    MOVEEND_UPDATE_LAST_MOVES_OPPOSING_SIDE,
    MOVEEND_MIRROR_MOVE_OPPOSING_SIDE,
    MOVEEND_NEXT_TARGET, // Everything up until here is handled for each strike of a spread move
    // Check all battlers
    MOVEEND_BOUNCED_MOVE,
    MOVEEND_MULTIHIT_MOVE_BLOCK, // HP threshold items, effectiveness message, end move
    MOVEEND_DEFROST,
    MOVEEND_MOVE_BLOCK_RECOIL, // Recoil effects should still happen even if Sheer Force applies
    MOVEEND_SHEER_FORCE, // If move is Sheer Force affected, jump to effects that are not suppressed
    MOVEEND_MOVE_BLOCK,
    MOVEEND_ITEM_EFFECTS_ATTACKER_2,
    MOVEEND_ABILITY_EFFECT_FOES_FAINTED, // Moxie-like abilities / Battle Bond / Magician
    MOVEEND_SHELL_TRAP,
    MOVEEND_COLOR_CHANGE, // Color Change / Berserk / Anger Shell
    MOVEEND_KEE_MARANGA_HP_THRESHOLD_ITEM_TARGET,
    MOVEEND_CARD_BUTTON, // Red Card / Eject Button
    MOVEEND_FORM_CHANGE,
    MOVEEND_LIFE_ORB_SHELL_BELL,
    MOVEEND_EMERGENCY_EXIT,
    MOVEEND_HIT_ESCAPE,
    MOVEEND_PICKPOCKET,
    MOVEEND_ITEMS_EFFECTS_ALL,
    MOVEEND_OPPORTUNIST,
    MOVEEND_THIRD_MOVE_BLOCK,
    MOVEEND_RAMPAGE,
    MOVEEND_CONFUSION_AFTER_SKY_DROP, // If target was previously rampaging, it should be confused when dropped
    MOVEEND_SPRAY_LEPPA_BLUNDER, // Throat Spray, Leppa Berry, Blunder Policy
    MOVEEND_ITEM_ON_STAT_CHANGE,
    MOVEEND_SEND_OUT_REPLACEMENTS, // For all non-forced switching effects
    MOVEEND_CLEAR_BITS,
    MOVEEND_DANCER,
    MOVEEND_PURSUIT_NEXT_ACTION,
    MOVEEND_COUNT,

    // This guarantees a correct jump if new moveends are added directly after MOVEEND_HIT_ESCAPE
    MOVEEND_JUMP_TO_HIT_ESCAPE_PLUS_ONE = (MOVEEND_HIT_ESCAPE + 1),
};

enum MoveResult
{
    MOVE_RESULT_CONTINUE,
    MOVE_RESULT_RUN_SCRIPT_INCREMENT,
    MOVE_RESULT_RUN_SCRIPT,
    MOVE_RESULT_FAILURE,
    MOVE_RESULT_DONE,
};

enum StatChangeResolution
{
    STAT_CHANGE_SUBSTITUTE,
    STAT_CHANGE_CAN_ANY_CHANGE,
    STAT_CHANGE_ACCURACY,
    STAT_CHANGE_MIRROR_ARMOR,
    STAT_CHANGE_BEFORE_CHANGE,
    STAT_CHANGE_TRY_CHANGE,
    STAT_CHANGE_COUNT,
};

enum ProtectBypass
{
    PROTECT_BYPASS_NONE,
    PROTECT_BYPASS_MOVE_IGNORES,
    PROTECT_BYPASS_ABILITY_IGNORES,
    PROTECT_BYPASS_OTHER,
};

#endif // GUARD_CONSTANTS_BATTLE_MOVE_RESOLUTION_H
