#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#include "metaprogram.h"
#include "constants/tms_hms.h"

enum __attribute__((packed)) Item
{
    ITEM_NONE = 0,

    // Poké Balls
    ITEM_POKE_BALL = 1,
    ITEM_GREAT_BALL = 2,
    ITEM_ULTRA_BALL = 3,
    ITEM_MASTER_BALL = 4,
    ITEM_PREMIER_BALL = 5,
    ITEM_HEAL_BALL = 6,
    ITEM_NET_BALL = 7,
    ITEM_NEST_BALL = 8,
    ITEM_DIVE_BALL = 9,
    ITEM_DUSK_BALL = 10,
    ITEM_TIMER_BALL = 11,
    ITEM_QUICK_BALL = 12,
    ITEM_REPEAT_BALL = 13,
    ITEM_LUXURY_BALL = 14,
    ITEM_LEVEL_BALL = 15,
    ITEM_LURE_BALL = 16,
    ITEM_MOON_BALL = 17,
    ITEM_FRIEND_BALL = 18,
    ITEM_LOVE_BALL = 19,
    ITEM_FAST_BALL = 20,
    ITEM_HEAVY_BALL = 21,
    ITEM_DREAM_BALL = 22,
    ITEM_SAFARI_BALL = 23,
    ITEM_SPORT_BALL = 24,
    ITEM_PARK_BALL = 25,
    ITEM_BEAST_BALL = 26,
    ITEM_CHERISH_BALL = 27,

    // Medicine
    ITEM_POTION = 28,
    ITEM_SUPER_POTION = 29,
    ITEM_HYPER_POTION = 30,
    ITEM_MAX_POTION = 31,
    ITEM_FULL_RESTORE = 32,
    ITEM_REVIVE = 33,
    ITEM_MAX_REVIVE = 34,
    ITEM_FRESH_WATER = 35,
    ITEM_SODA_POP = 36,
    ITEM_LEMONADE = 37,
    ITEM_MOOMOO_MILK = 38,
    ITEM_ENERGY_POWDER = 39,
    ITEM_ENERGYPOWDER = ITEM_ENERGY_POWDER, // Pre-Gen VI name
    ITEM_ENERGY_ROOT = 40,
    ITEM_HEAL_POWDER = 41,
    ITEM_REVIVAL_HERB = 42,
    ITEM_ANTIDOTE = 43,
    ITEM_PARALYZE_HEAL = 44,
    ITEM_PARLYZ_HEAL = ITEM_PARALYZE_HEAL, // Pre-Gen VI name
    ITEM_BURN_HEAL = 45,
    ITEM_ICE_HEAL = 46,
    ITEM_AWAKENING = 47,
    ITEM_FULL_HEAL = 48,
    ITEM_ETHER = 49,
    ITEM_MAX_ETHER = 50,
    ITEM_ELIXIR = 51,
    ITEM_ELIXER = ITEM_ELIXIR, // Pre-Gen III name
    ITEM_MAX_ELIXIR = 52,
    ITEM_MAX_ELIXER = ITEM_MAX_ELIXIR, // Pre-Gen III name
    ITEM_BERRY_JUICE = 53,
    ITEM_SACRED_ASH = 54,
    ITEM_SWEET_HEART = 55,
    ITEM_MAX_HONEY = 56,

    // Regional Specialties
    ITEM_PEWTER_CRUNCHIES = 57,
    ITEM_RAGE_CANDY_BAR = 58,
    ITEM_RAGECANDYBAR = ITEM_RAGE_CANDY_BAR, // Pre-Gen VI name
    ITEM_LAVA_COOKIE = 59,
    ITEM_OLD_GATEAU = 60,
    ITEM_CASTELIACONE = 61,
    ITEM_LUMIOSE_GALETTE = 62,
    ITEM_SHALOUR_SABLE = 63,
    ITEM_BIG_MALASADA = 64,

    // Vitamins
    ITEM_HP_UP = 65,
    ITEM_PROTEIN = 66,
    ITEM_IRON = 67,
    ITEM_CALCIUM = 68,
    ITEM_ZINC = 69,
    ITEM_CARBOS = 70,
    ITEM_PP_UP = 71,
    ITEM_PP_MAX = 72,

    // EV Feathers
    ITEM_HEALTH_FEATHER = 73,
    ITEM_HEALTH_WING = ITEM_HEALTH_FEATHER, // Pre-Gen VIII name
    ITEM_MUSCLE_FEATHER = 74,
    ITEM_MUSCLE_WING = ITEM_MUSCLE_FEATHER, // Pre-Gen VIII name
    ITEM_RESIST_FEATHER = 75,
    ITEM_RESIST_WING = ITEM_RESIST_FEATHER, // Pre-Gen VIII name
    ITEM_GENIUS_FEATHER = 76,
    ITEM_GENIUS_WING = ITEM_GENIUS_FEATHER, // Pre-Gen VIII name
    ITEM_CLEVER_FEATHER = 77,
    ITEM_CLEVER_WING = ITEM_CLEVER_FEATHER, // Pre-Gen VIII name
    ITEM_SWIFT_FEATHER = 78,
    ITEM_SWIFT_WING = ITEM_SWIFT_FEATHER, // Pre-Gen VIII name

    // Ability Modifiers
    ITEM_ABILITY_CAPSULE = 79,
    ITEM_ABILITY_PATCH = 80,

    // Mints
    ITEM_LONELY_MINT = 81,
    ITEM_ADAMANT_MINT = 82,
    ITEM_NAUGHTY_MINT = 83,
    ITEM_BRAVE_MINT = 84,
    ITEM_BOLD_MINT = 85,
    ITEM_IMPISH_MINT = 86,
    ITEM_LAX_MINT = 87,
    ITEM_RELAXED_MINT = 88,
    ITEM_MODEST_MINT = 89,
    ITEM_MILD_MINT = 90,
    ITEM_RASH_MINT = 91,
    ITEM_QUIET_MINT = 92,
    ITEM_CALM_MINT = 93,
    ITEM_GENTLE_MINT = 94,
    ITEM_CAREFUL_MINT = 95,
    ITEM_SASSY_MINT = 96,
    ITEM_TIMID_MINT = 97,
    ITEM_HASTY_MINT = 98,
    ITEM_JOLLY_MINT = 99,
    ITEM_NAIVE_MINT = 100,
    ITEM_SERIOUS_MINT = 101,

    // Candy
    ITEM_RARE_CANDY = 102,
    ITEM_EXP_CANDY_XS = 103,
    ITEM_EXP_CANDY_S = 104,
    ITEM_EXP_CANDY_M = 105,
    ITEM_EXP_CANDY_L = 106,
    ITEM_EXP_CANDY_XL = 107,
    ITEM_DYNAMAX_CANDY = 108,

    // Medicinal Flutes
    ITEM_BLUE_FLUTE = 109,
    ITEM_YELLOW_FLUTE = 110,
    ITEM_RED_FLUTE = 111,

    // Encounter-modifying Flutes
    ITEM_BLACK_FLUTE = 112,
    ITEM_WHITE_FLUTE = 113,

    // Encounter Modifiers
    ITEM_REPEL = 114,
    ITEM_SUPER_REPEL = 115,
    ITEM_MAX_REPEL = 116,
    ITEM_LURE = 117,
    ITEM_SUPER_LURE = 118,
    ITEM_MAX_LURE = 119,

    ITEM_ESCAPE_ROPE = 120,

    // X Items
    ITEM_X_ATTACK = 121,
    ITEM_X_DEFENSE = 122,
    ITEM_X_DEFEND = ITEM_X_DEFENSE, // Pre-Gen VI name
    ITEM_X_SP_ATK = 123,
    ITEM_X_SPECIAL = ITEM_X_SP_ATK, // Pre-Gen VI name
    ITEM_X_SP_DEF = 124,
    ITEM_X_SPEED = 125,
    ITEM_X_ACCURACY = 126,

    ITEM_DIRE_HIT = 127,
    ITEM_GUARD_SPEC = 128,

    // Escape Items
    ITEM_POKE_DOLL = 129,
    ITEM_FLUFFY_TAIL = 130,
    ITEM_POKE_TOY = 131,

    ITEM_MAX_MUSHROOMS = 132,

    // Treasures
    ITEM_BOTTLE_CAP = 133,
    ITEM_GOLD_BOTTLE_CAP = 134,
    ITEM_NUGGET = 135,
    ITEM_BIG_NUGGET = 136,
    ITEM_TINY_MUSHROOM = 137,
    ITEM_TINYMUSHROOM = ITEM_TINY_MUSHROOM, // Pre-Gen VI name
    ITEM_BIG_MUSHROOM = 138,
    ITEM_BALM_MUSHROOM = 139,
    ITEM_BALMMUSHROOM = ITEM_BALM_MUSHROOM, // Pre-Gen VI name
    ITEM_PEARL = 140,
    ITEM_BIG_PEARL = 141,
    ITEM_PEARL_STRING = 142,
    ITEM_STARDUST = 143,
    ITEM_STAR_PIECE = 144,
    ITEM_COMET_SHARD = 145,
    ITEM_SHOAL_SALT = 146,
    ITEM_SHOAL_SHELL = 147,
    ITEM_RED_SHARD = 148,
    ITEM_BLUE_SHARD = 149,
    ITEM_YELLOW_SHARD = 150,
    ITEM_GREEN_SHARD = 151,
    ITEM_HEART_SCALE = 152,
    ITEM_HONEY = 153,
    ITEM_RARE_BONE = 154,
    ITEM_ODD_KEYSTONE = 155,
    ITEM_PRETTY_FEATHER = 156,
    ITEM_PRETTY_WING = ITEM_PRETTY_FEATHER, // Pre-Gen VIII name
    ITEM_RELIC_COPPER = 157,
    ITEM_RELIC_SILVER = 158,
    ITEM_RELIC_GOLD = 159,
    ITEM_RELIC_VASE = 160,
    ITEM_RELIC_BAND = 161,
    ITEM_RELIC_STATUE = 162,
    ITEM_RELIC_CROWN = 163,
    ITEM_STRANGE_SOUVENIR = 164,

    // Fossils
    ITEM_HELIX_FOSSIL = 165,
    ITEM_DOME_FOSSIL = 166,
    ITEM_OLD_AMBER = 167,
    ITEM_ROOT_FOSSIL = 168,
    ITEM_CLAW_FOSSIL = 169,
    ITEM_ARMOR_FOSSIL = 170,
    ITEM_SKULL_FOSSIL = 171,
    ITEM_COVER_FOSSIL = 172,
    ITEM_PLUME_FOSSIL = 173,
    ITEM_JAW_FOSSIL = 174,
    ITEM_SAIL_FOSSIL = 175,
    ITEM_FOSSILIZED_BIRD = 176,
    ITEM_FOSSILIZED_FISH = 177,
    ITEM_FOSSILIZED_DRAKE = 178,
    ITEM_FOSSILIZED_DINO = 179,

    // Mulch
    ITEM_GROWTH_MULCH = 180,
    ITEM_DAMP_MULCH = 181,
    ITEM_STABLE_MULCH = 182,
    ITEM_GOOEY_MULCH = 183,
    ITEM_RICH_MULCH = 184,
    ITEM_SURPRISE_MULCH = 185,
    ITEM_BOOST_MULCH = 186,
    ITEM_AMAZE_MULCH = 187,

    // Apricorns
    ITEM_RED_APRICORN = 188,
    ITEM_BLUE_APRICORN = 189,
    ITEM_BLU_APRICORN = ITEM_BLUE_APRICORN, // Pre-Gen VI name
    ITEM_YELLOW_APRICORN = 190,
    ITEM_YLW_APRICORN = ITEM_YELLOW_APRICORN, // Pre-Gen VI name
    ITEM_GREEN_APRICORN = 191,
    ITEM_GRN_APRICORN = ITEM_GREEN_APRICORN, // Pre-Gen VI name
    ITEM_PINK_APRICORN = 192,
    ITEM_PNK_APRICORN = ITEM_PINK_APRICORN, // Pre-Gen VI name
    ITEM_WHITE_APRICORN = 193,
    ITEM_WHT_APRICORN = ITEM_WHITE_APRICORN, // Pre-Gen VI name
    ITEM_BLACK_APRICORN = 194,
    ITEM_BLK_APRICORN = ITEM_BLACK_APRICORN, // Pre-Gen VI name

    ITEM_WISHING_PIECE = 195,
    ITEM_GALARICA_TWIG = 196,
    ITEM_ARMORITE_ORE = 197,
    ITEM_DYNITE_ORE = 198,

    // Mail
    FIRST_MAIL_INDEX = 199,
    ITEM_ORANGE_MAIL = FIRST_MAIL_INDEX,
    ITEM_HARBOR_MAIL = 200,
    ITEM_GLITTER_MAIL = 201,
    ITEM_MECH_MAIL = 202,
    ITEM_WOOD_MAIL = 203,
    ITEM_WAVE_MAIL = 204,
    ITEM_BEAD_MAIL = 205,
    ITEM_SHADOW_MAIL = 206,
    ITEM_TROPIC_MAIL = 207,
    ITEM_DREAM_MAIL = 208,
    ITEM_FAB_MAIL = 209,
    ITEM_RETRO_MAIL = 210,

    // Evolution Items
    ITEM_FIRE_STONE = 211,
    ITEM_WATER_STONE = 212,
    ITEM_THUNDER_STONE = 213,
    ITEM_THUNDERSTONE = ITEM_THUNDER_STONE, // Pre-Gen VI name
    ITEM_LEAF_STONE = 214,
    ITEM_ICE_STONE = 215,
    ITEM_SUN_STONE = 216,
    ITEM_MOON_STONE = 217,
    ITEM_SHINY_STONE = 218,
    ITEM_DUSK_STONE = 219,
    ITEM_DAWN_STONE = 220,
    ITEM_SWEET_APPLE = 221,
    ITEM_TART_APPLE = 222,
    ITEM_CRACKED_POT = 223,
    ITEM_CHIPPED_POT = 224,
    ITEM_GALARICA_CUFF = 225,
    ITEM_GALARICA_WREATH = 226,
    ITEM_DRAGON_SCALE = 227,
    ITEM_UPGRADE = 228,
    ITEM_UP_GRADE = ITEM_UPGRADE, // Pre-Gen VIII name
    ITEM_PROTECTOR = 229,
    ITEM_ELECTIRIZER = 230,
    ITEM_MAGMARIZER = 231,
    ITEM_DUBIOUS_DISC = 232,
    ITEM_REAPER_CLOTH = 233,
    ITEM_PRISM_SCALE = 234,
    ITEM_WHIPPED_DREAM = 235,
    ITEM_SACHET = 236,
    ITEM_OVAL_STONE = 237,
    ITEM_STRAWBERRY_SWEET = 238,
    ITEM_LOVE_SWEET = 239,
    ITEM_BERRY_SWEET = 240,
    ITEM_CLOVER_SWEET = 241,
    ITEM_FLOWER_SWEET = 242,
    ITEM_STAR_SWEET = 243,
    ITEM_RIBBON_SWEET = 244,

    ITEM_EVERSTONE = 245,

    // Nectars
    ITEM_RED_NECTAR = 246,
    ITEM_YELLOW_NECTAR = 247,
    ITEM_PINK_NECTAR = 248,
    ITEM_PURPLE_NECTAR = 249,

    // Plates
    ITEM_FLAME_PLATE = 250,
    ITEM_SPLASH_PLATE = 251,
    ITEM_ZAP_PLATE = 252,
    ITEM_MEADOW_PLATE = 253,
    ITEM_ICICLE_PLATE = 254,
    ITEM_FIST_PLATE = 255,
    ITEM_TOXIC_PLATE = 256,
    ITEM_EARTH_PLATE = 257,
    ITEM_SKY_PLATE = 258,
    ITEM_MIND_PLATE = 259,
    ITEM_INSECT_PLATE = 260,
    ITEM_STONE_PLATE = 261,
    ITEM_SPOOKY_PLATE = 262,
    ITEM_DRACO_PLATE = 263,
    ITEM_DREAD_PLATE = 264,
    ITEM_IRON_PLATE = 265,
    ITEM_PIXIE_PLATE = 266,

    // Drives
    ITEM_DOUSE_DRIVE = 267,
    ITEM_SHOCK_DRIVE = 268,
    ITEM_BURN_DRIVE = 269,
    ITEM_CHILL_DRIVE = 270,

    // Memories
    ITEM_FIRE_MEMORY = 271,
    ITEM_WATER_MEMORY = 272,
    ITEM_ELECTRIC_MEMORY = 273,
    ITEM_GRASS_MEMORY = 274,
    ITEM_ICE_MEMORY = 275,
    ITEM_FIGHTING_MEMORY = 276,
    ITEM_POISON_MEMORY = 277,
    ITEM_GROUND_MEMORY = 278,
    ITEM_FLYING_MEMORY = 279,
    ITEM_PSYCHIC_MEMORY = 280,
    ITEM_BUG_MEMORY = 281,
    ITEM_ROCK_MEMORY = 282,
    ITEM_GHOST_MEMORY = 283,
    ITEM_DRAGON_MEMORY = 284,
    ITEM_DARK_MEMORY = 285,
    ITEM_STEEL_MEMORY = 286,
    ITEM_FAIRY_MEMORY = 287,

    ITEM_RUSTED_SWORD = 288,
    ITEM_RUSTED_SHIELD = 289,

    // Colored Orbs
    ITEM_RED_ORB = 290,
    ITEM_BLUE_ORB = 291,

    // Mega Stones
    ITEM_VENUSAURITE = 292,
    ITEM_CHARIZARDITE_X = 293,
    ITEM_CHARIZARDITE_Y = 294,
    ITEM_BLASTOISINITE = 295,
    ITEM_BEEDRILLITE = 296,
    ITEM_PIDGEOTITE = 297,
    ITEM_ALAKAZITE = 298,
    ITEM_SLOWBRONITE = 299,
    ITEM_GENGARITE = 300,
    ITEM_KANGASKHANITE = 301,
    ITEM_PINSIRITE = 302,
    ITEM_GYARADOSITE = 303,
    ITEM_AERODACTYLITE = 304,
    ITEM_MEWTWONITE_X = 305,
    ITEM_MEWTWONITE_Y = 306,
    ITEM_AMPHAROSITE = 307,
    ITEM_STEELIXITE = 308,
    ITEM_SCIZORITE = 309,
    ITEM_HERACRONITE = 310,
    ITEM_HOUNDOOMINITE = 311,
    ITEM_TYRANITARITE = 312,
    ITEM_SCEPTILITE = 313,
    ITEM_BLAZIKENITE = 314,
    ITEM_SWAMPERTITE = 315,
    ITEM_GARDEVOIRITE = 316,
    ITEM_SABLENITE = 317,
    ITEM_MAWILITE = 318,
    ITEM_AGGRONITE = 319,
    ITEM_MEDICHAMITE = 320,
    ITEM_MANECTITE = 321,
    ITEM_SHARPEDONITE = 322,
    ITEM_CAMERUPTITE = 323,
    ITEM_ALTARIANITE = 324,
    ITEM_BANETTITE = 325,
    ITEM_ABSOLITE = 326,
    ITEM_GLALITITE = 327,
    ITEM_SALAMENCITE = 328,
    ITEM_METAGROSSITE = 329,
    ITEM_LATIASITE = 330,
    ITEM_LATIOSITE = 331,
    ITEM_LOPUNNITE = 332,
    ITEM_GARCHOMPITE = 333,
    ITEM_LUCARIONITE = 334,
    ITEM_ABOMASITE = 335,
    ITEM_GALLADITE = 336,
    ITEM_AUDINITE = 337,
    ITEM_DIANCITE = 338,

    // Gems
    ITEM_NORMAL_GEM = 339,
    ITEM_FIRE_GEM = 340,
    ITEM_WATER_GEM = 341,
    ITEM_ELECTRIC_GEM = 342,
    ITEM_GRASS_GEM = 343,
    ITEM_ICE_GEM = 344,
    ITEM_FIGHTING_GEM = 345,
    ITEM_POISON_GEM = 346,
    ITEM_GROUND_GEM = 347,
    ITEM_FLYING_GEM = 348,
    ITEM_PSYCHIC_GEM = 349,
    ITEM_BUG_GEM = 350,
    ITEM_ROCK_GEM = 351,
    ITEM_GHOST_GEM = 352,
    ITEM_DRAGON_GEM = 353,
    ITEM_DARK_GEM = 354,
    ITEM_STEEL_GEM = 355,
    ITEM_FAIRY_GEM = 356,

    // Z-Crystals
    ITEM_NORMALIUM_Z = 357,
    ITEM_FIRIUM_Z = 358,
    ITEM_WATERIUM_Z = 359,
    ITEM_ELECTRIUM_Z = 360,
    ITEM_GRASSIUM_Z = 361,
    ITEM_ICIUM_Z = 362,
    ITEM_FIGHTINIUM_Z = 363,
    ITEM_POISONIUM_Z = 364,
    ITEM_GROUNDIUM_Z = 365,
    ITEM_FLYINIUM_Z = 366,
    ITEM_PSYCHIUM_Z = 367,
    ITEM_BUGINIUM_Z = 368,
    ITEM_ROCKIUM_Z = 369,
    ITEM_GHOSTIUM_Z = 370,
    ITEM_DRAGONIUM_Z = 371,
    ITEM_DARKINIUM_Z = 372,
    ITEM_STEELIUM_Z = 373,
    ITEM_FAIRIUM_Z = 374,
    ITEM_PIKANIUM_Z = 375,
    ITEM_EEVIUM_Z = 376,
    ITEM_SNORLIUM_Z = 377,
    ITEM_MEWNIUM_Z = 378,
    ITEM_DECIDIUM_Z = 379,
    ITEM_INCINIUM_Z = 380,
    ITEM_PRIMARIUM_Z = 381,
    ITEM_LYCANIUM_Z = 382,
    ITEM_MIMIKIUM_Z = 383,
    ITEM_KOMMONIUM_Z = 384,
    ITEM_TAPUNIUM_Z = 385,
    ITEM_SOLGANIUM_Z = 386,
    ITEM_LUNALIUM_Z = 387,
    ITEM_MARSHADIUM_Z = 388,
    ITEM_ALORAICHIUM_Z = 389,
    ITEM_PIKASHUNIUM_Z = 390,
    ITEM_ULTRANECROZIUM_Z = 391,

    // Species-specific Held Items
    ITEM_LIGHT_BALL = 392,
    ITEM_LEEK = 393,
    ITEM_STICK = ITEM_LEEK, // Pre-Gen VIII name
    ITEM_THICK_CLUB = 394,
    ITEM_LUCKY_PUNCH = 395,
    ITEM_METAL_POWDER = 396,
    ITEM_QUICK_POWDER = 397,
    ITEM_DEEP_SEA_SCALE = 398,
    ITEM_DEEPSEASCALE = ITEM_DEEP_SEA_SCALE, // Pre-Gen VI name
    ITEM_DEEP_SEA_TOOTH = 399,
    ITEM_DEEPSEATOOTH = ITEM_DEEP_SEA_TOOTH, // Pre-Gen VI name
    ITEM_SOUL_DEW = 400,
    ITEM_ADAMANT_ORB = 401,
    ITEM_LUSTROUS_ORB = 402,
    ITEM_GRISEOUS_ORB = 403,

    // Incenses
    ITEM_SEA_INCENSE = 404,
    ITEM_LAX_INCENSE = 405,
    ITEM_ODD_INCENSE = 406,
    ITEM_ROCK_INCENSE = 407,
    ITEM_FULL_INCENSE = 408,
    ITEM_WAVE_INCENSE = 409,
    ITEM_ROSE_INCENSE = 410,
    ITEM_LUCK_INCENSE = 411,
    ITEM_PURE_INCENSE = 412,

    // Contest Scarves
    ITEM_RED_SCARF = 413,
    ITEM_BLUE_SCARF = 414,
    ITEM_PINK_SCARF = 415,
    ITEM_GREEN_SCARF = 416,
    ITEM_YELLOW_SCARF = 417,

    // EV Gain Modifiers
    ITEM_MACHO_BRACE = 418,
    ITEM_POWER_WEIGHT = 419,
    ITEM_POWER_BRACER = 420,
    ITEM_POWER_BELT = 421,
    ITEM_POWER_LENS = 422,
    ITEM_POWER_BAND = 423,
    ITEM_POWER_ANKLET = 424,

    // Type-boosting Held Items
    ITEM_SILK_SCARF = 425,
    ITEM_CHARCOAL = 426,
    ITEM_MYSTIC_WATER = 427,
    ITEM_MAGNET = 428,
    ITEM_MIRACLE_SEED = 429,
    ITEM_NEVER_MELT_ICE = 430,
    ITEM_NEVERMELTICE = ITEM_NEVER_MELT_ICE, // Pre-Gen VI name
    ITEM_BLACK_BELT = 431,
    ITEM_BLACKBELT = ITEM_BLACK_BELT, // Gen II name
    ITEM_POISON_BARB = 432,
    ITEM_SOFT_SAND = 433,
    ITEM_SHARP_BEAK = 434,
    ITEM_TWISTED_SPOON = 435,
    ITEM_TWISTEDSPOON = ITEM_TWISTED_SPOON, // Pre-Gen VI name
    ITEM_SILVER_POWDER = 436,
    ITEM_SILVERPOWDER = ITEM_SILVER_POWDER, // Pre-Gen VI name
    ITEM_HARD_STONE = 437,
    ITEM_SPELL_TAG = 438,
    ITEM_DRAGON_FANG = 439,
    ITEM_BLACK_GLASSES = 440,
    ITEM_BLACKGLASSES = ITEM_BLACK_GLASSES, // Pre-Gen VI name
    ITEM_METAL_COAT = 441,

    // Choice Items
    ITEM_CHOICE_BAND = 442,
    ITEM_CHOICE_SPECS = 443,
    ITEM_CHOICE_SCARF = 444,

    // Status Orbs
    ITEM_FLAME_ORB = 445,
    ITEM_TOXIC_ORB = 446,

    // Weather Rocks
    ITEM_DAMP_ROCK = 447,
    ITEM_HEAT_ROCK = 448,
    ITEM_SMOOTH_ROCK = 449,
    ITEM_ICY_ROCK = 450,

    // Terrain Seeds
    ITEM_ELECTRIC_SEED = 451,
    ITEM_PSYCHIC_SEED = 452,
    ITEM_MISTY_SEED = 453,
    ITEM_GRASSY_SEED = 454,

    // Type-activated Stat Modifiers
    ITEM_ABSORB_BULB = 455,
    ITEM_CELL_BATTERY = 456,
    ITEM_LUMINOUS_MOSS = 457,
    ITEM_SNOWBALL = 458,

    // Misc. Held Items
    ITEM_BRIGHT_POWDER = 459,
    ITEM_BRIGHTPOWDER = ITEM_BRIGHT_POWDER, // Pre-Gen VI name
    ITEM_WHITE_HERB = 460,
    ITEM_EXP_SHARE = 461,
    ITEM_EXP_ALL = ITEM_EXP_SHARE, // Gen I name
    ITEM_QUICK_CLAW = 462,
    ITEM_SOOTHE_BELL = 463,
    ITEM_MENTAL_HERB = 464,
    ITEM_KINGS_ROCK = 465,
    ITEM_AMULET_COIN = 466,
    ITEM_CLEANSE_TAG = 467,
    ITEM_SMOKE_BALL = 468,
    ITEM_FOCUS_BAND = 469,
    ITEM_LUCKY_EGG = 470,
    ITEM_SCOPE_LENS = 471,
    ITEM_LEFTOVERS = 472,
    ITEM_SHELL_BELL = 473,
    ITEM_WIDE_LENS = 474,
    ITEM_MUSCLE_BAND = 475,
    ITEM_WISE_GLASSES = 476,
    ITEM_EXPERT_BELT = 477,
    ITEM_LIGHT_CLAY = 478,
    ITEM_LIFE_ORB = 479,
    ITEM_POWER_HERB = 480,
    ITEM_FOCUS_SASH = 481,
    ITEM_ZOOM_LENS = 482,
    ITEM_METRONOME = 483,
    ITEM_IRON_BALL = 484,
    ITEM_LAGGING_TAIL = 485,
    ITEM_DESTINY_KNOT = 486,
    ITEM_BLACK_SLUDGE = 487,
    ITEM_GRIP_CLAW = 488,
    ITEM_STICKY_BARB = 489,
    ITEM_SHED_SHELL = 490,
    ITEM_BIG_ROOT = 491,
    ITEM_RAZOR_CLAW = 492,
    ITEM_RAZOR_FANG = 493,
    ITEM_EVIOLITE = 494,
    ITEM_FLOAT_STONE = 495,
    ITEM_ROCKY_HELMET = 496,
    ITEM_AIR_BALLOON = 497,
    ITEM_RED_CARD = 498,
    ITEM_RING_TARGET = 499,
    ITEM_BINDING_BAND = 500,
    ITEM_EJECT_BUTTON = 501,
    ITEM_WEAKNESS_POLICY = 502,
    ITEM_ASSAULT_VEST = 503,
    ITEM_SAFETY_GOGGLES = 504,
    ITEM_ADRENALINE_ORB = 505,
    ITEM_TERRAIN_EXTENDER = 506,
    ITEM_PROTECTIVE_PADS = 507,
    ITEM_THROAT_SPRAY = 508,
    ITEM_EJECT_PACK = 509,
    ITEM_HEAVY_DUTY_BOOTS = 510,
    ITEM_BLUNDER_POLICY = 511,
    ITEM_ROOM_SERVICE = 512,
    ITEM_UTILITY_UMBRELLA = 513,

    // Berries
    FIRST_BERRY_INDEX = 514,
    ITEM_CHERI_BERRY = FIRST_BERRY_INDEX,
    ITEM_CHESTO_BERRY = 515,
    ITEM_PECHA_BERRY = 516,
    ITEM_RAWST_BERRY = 517,
    ITEM_ASPEAR_BERRY = 518,
    ITEM_LEPPA_BERRY = 519,
    ITEM_ORAN_BERRY = 520,
    ITEM_PERSIM_BERRY = 521,
    ITEM_LUM_BERRY = 522,
    ITEM_SITRUS_BERRY = 523,
    ITEM_FIGY_BERRY = 524,
    ITEM_WIKI_BERRY = 525,
    ITEM_MAGO_BERRY = 526,
    ITEM_AGUAV_BERRY = 527,
    ITEM_IAPAPA_BERRY = 528,
    ITEM_RAZZ_BERRY = 529,
    ITEM_BLUK_BERRY = 530,
    ITEM_NANAB_BERRY = 531,
    ITEM_WEPEAR_BERRY = 532,
    ITEM_PINAP_BERRY = 533,
    ITEM_POMEG_BERRY = 534,
    ITEM_KELPSY_BERRY = 535,
    ITEM_QUALOT_BERRY = 536,
    ITEM_HONDEW_BERRY = 537,
    ITEM_GREPA_BERRY = 538,
    ITEM_TAMATO_BERRY = 539,
    ITEM_CORNN_BERRY = 540,
    ITEM_MAGOST_BERRY = 541,
    ITEM_RABUTA_BERRY = 542,
    ITEM_NOMEL_BERRY = 543,
    ITEM_SPELON_BERRY = 544,
    ITEM_PAMTRE_BERRY = 545,
    ITEM_WATMEL_BERRY = 546,
    ITEM_DURIN_BERRY = 547,
    ITEM_BELUE_BERRY = 548,
    ITEM_CHILAN_BERRY = 549,
    ITEM_OCCA_BERRY = 550,
    ITEM_PASSHO_BERRY = 551,
    ITEM_WACAN_BERRY = 552,
    ITEM_RINDO_BERRY = 553,
    ITEM_YACHE_BERRY = 554,
    ITEM_CHOPLE_BERRY = 555,
    ITEM_KEBIA_BERRY = 556,
    ITEM_SHUCA_BERRY = 557,
    ITEM_COBA_BERRY = 558,
    ITEM_PAYAPA_BERRY = 559,
    ITEM_TANGA_BERRY = 560,
    ITEM_CHARTI_BERRY = 561,
    ITEM_KASIB_BERRY = 562,
    ITEM_HABAN_BERRY = 563,
    ITEM_COLBUR_BERRY = 564,
    ITEM_BABIRI_BERRY = 565,
    ITEM_ROSELI_BERRY = 566,
    ITEM_LIECHI_BERRY = 567,
    ITEM_GANLON_BERRY = 568,
    ITEM_SALAC_BERRY = 569,
    ITEM_PETAYA_BERRY = 570,
    ITEM_APICOT_BERRY = 571,
    ITEM_LANSAT_BERRY = 572,
    ITEM_STARF_BERRY = 573,
    ITEM_ENIGMA_BERRY = 574,
    ITEM_MICLE_BERRY = 575,
    ITEM_CUSTAP_BERRY = 576,
    ITEM_JABOCA_BERRY = 577,
    ITEM_ROWAP_BERRY = 578,
    ITEM_KEE_BERRY = 579,
    ITEM_MARANGA_BERRY = 580,
    ITEM_ENIGMA_BERRY_E_READER = 581,
    LAST_BERRY_INDEX =  ITEM_ENIGMA_BERRY_E_READER,

    // TMs/HMs
    ITEM_TM01 = (LAST_BERRY_INDEX + 1),
    ITEM_TM02 = (LAST_BERRY_INDEX + 2),
    ITEM_TM03 = (LAST_BERRY_INDEX + 3),
    ITEM_TM04 = (LAST_BERRY_INDEX + 4),
    ITEM_TM05 = (LAST_BERRY_INDEX + 5),
    ITEM_TM06 = (LAST_BERRY_INDEX + 6),
    ITEM_TM07 = (LAST_BERRY_INDEX + 7),
    ITEM_TM08 = (LAST_BERRY_INDEX + 8),
    ITEM_TM09 = (LAST_BERRY_INDEX + 9),
    ITEM_TM10 = (LAST_BERRY_INDEX + 10),
    ITEM_TM11 = (LAST_BERRY_INDEX + 11),
    ITEM_TM12 = (LAST_BERRY_INDEX + 12),
    ITEM_TM13 = (LAST_BERRY_INDEX + 13),
    ITEM_TM14 = (LAST_BERRY_INDEX + 14),
    ITEM_TM15 = (LAST_BERRY_INDEX + 15),
    ITEM_TM16 = (LAST_BERRY_INDEX + 16),
    ITEM_TM17 = (LAST_BERRY_INDEX + 17),
    ITEM_TM18 = (LAST_BERRY_INDEX + 18),
    ITEM_TM19 = (LAST_BERRY_INDEX + 19),
    ITEM_TM20 = (LAST_BERRY_INDEX + 20),
    ITEM_TM21 = (LAST_BERRY_INDEX + 21),
    ITEM_TM22 = (LAST_BERRY_INDEX + 22),
    ITEM_TM23 = (LAST_BERRY_INDEX + 23),
    ITEM_TM24 = (LAST_BERRY_INDEX + 24),
    ITEM_TM25 = (LAST_BERRY_INDEX + 25),
    ITEM_TM26 = (LAST_BERRY_INDEX + 26),
    ITEM_TM27 = (LAST_BERRY_INDEX + 27),
    ITEM_TM28 = (LAST_BERRY_INDEX + 28),
    ITEM_TM29 = (LAST_BERRY_INDEX + 29),
    ITEM_TM30 = (LAST_BERRY_INDEX + 30),
    ITEM_TM31 = (LAST_BERRY_INDEX + 31),
    ITEM_TM32 = (LAST_BERRY_INDEX + 32),
    ITEM_TM33 = (LAST_BERRY_INDEX + 33),
    ITEM_TM34 = (LAST_BERRY_INDEX + 34),
    ITEM_TM35 = (LAST_BERRY_INDEX + 35),
    ITEM_TM36 = (LAST_BERRY_INDEX + 36),
    ITEM_TM37 = (LAST_BERRY_INDEX + 37),
    ITEM_TM38 = (LAST_BERRY_INDEX + 38),
    ITEM_TM39 = (LAST_BERRY_INDEX + 39),
    ITEM_TM40 = (LAST_BERRY_INDEX + 40),
    ITEM_TM41 = (LAST_BERRY_INDEX + 41),
    ITEM_TM42 = (LAST_BERRY_INDEX + 42),
    ITEM_TM43 = (LAST_BERRY_INDEX + 43),
    ITEM_TM44 = (LAST_BERRY_INDEX + 44),
    ITEM_TM45 = (LAST_BERRY_INDEX + 45),
    ITEM_TM46 = (LAST_BERRY_INDEX + 46),
    ITEM_TM47 = (LAST_BERRY_INDEX + 47),
    ITEM_TM48 = (LAST_BERRY_INDEX + 48),
    ITEM_TM49 = (LAST_BERRY_INDEX + 49),
    ITEM_TM50 = (LAST_BERRY_INDEX + 50),
    ITEM_TM51 = (LAST_BERRY_INDEX + 51),
    ITEM_TM52 = (LAST_BERRY_INDEX + 52),
    ITEM_TM53 = (LAST_BERRY_INDEX + 53),
    ITEM_TM54 = (LAST_BERRY_INDEX + 54),
    ITEM_TM55 = (LAST_BERRY_INDEX + 55),
    ITEM_TM56 = (LAST_BERRY_INDEX + 56),
    ITEM_TM57 = (LAST_BERRY_INDEX + 57),
    ITEM_TM58 = (LAST_BERRY_INDEX + 58),
    ITEM_TM59 = (LAST_BERRY_INDEX + 59),
    ITEM_TM60 = (LAST_BERRY_INDEX + 60),
    ITEM_TM61 = (LAST_BERRY_INDEX + 61),
    ITEM_TM62 = (LAST_BERRY_INDEX + 62),
    ITEM_TM63 = (LAST_BERRY_INDEX + 63),
    ITEM_TM64 = (LAST_BERRY_INDEX + 64),
    ITEM_TM65 = (LAST_BERRY_INDEX + 65),
    ITEM_TM66 = (LAST_BERRY_INDEX + 66),
    ITEM_TM67 = (LAST_BERRY_INDEX + 67),
    ITEM_TM68 = (LAST_BERRY_INDEX + 68),
    ITEM_TM69 = (LAST_BERRY_INDEX + 69),
    ITEM_TM70 = (LAST_BERRY_INDEX + 70),
    ITEM_TM71 = (LAST_BERRY_INDEX + 71),
    ITEM_TM72 = (LAST_BERRY_INDEX + 72),
    ITEM_TM73 = (LAST_BERRY_INDEX + 73),
    ITEM_TM74 = (LAST_BERRY_INDEX + 74),
    ITEM_TM75 = (LAST_BERRY_INDEX + 75),
    ITEM_TM76 = (LAST_BERRY_INDEX + 76),
    ITEM_TM77 = (LAST_BERRY_INDEX + 77),
    ITEM_TM78 = (LAST_BERRY_INDEX + 78),
    ITEM_TM79 = (LAST_BERRY_INDEX + 79),
    ITEM_TM80 = (LAST_BERRY_INDEX + 80),
    ITEM_TM81 = (LAST_BERRY_INDEX + 81),
    ITEM_TM82 = (LAST_BERRY_INDEX + 82),
    ITEM_TM83 = (LAST_BERRY_INDEX + 83),
    ITEM_TM84 = (LAST_BERRY_INDEX + 84),
    ITEM_TM85 = (LAST_BERRY_INDEX + 85),
    ITEM_TM86 = (LAST_BERRY_INDEX + 86),
    ITEM_TM87 = (LAST_BERRY_INDEX + 87),
    ITEM_TM88 = (LAST_BERRY_INDEX + 88),
    ITEM_TM89 = (LAST_BERRY_INDEX + 89),
    ITEM_TM90 = (LAST_BERRY_INDEX + 90),
    ITEM_TM91 = (LAST_BERRY_INDEX + 91),
    ITEM_TM92 = (LAST_BERRY_INDEX + 92),
    ITEM_TM93 = (LAST_BERRY_INDEX + 93),
    ITEM_TM94 = (LAST_BERRY_INDEX + 94),
    ITEM_TM95 = (LAST_BERRY_INDEX + 95),
    ITEM_TM96 = (LAST_BERRY_INDEX + 96),
    ITEM_TM97 = (LAST_BERRY_INDEX + 97),
    ITEM_TM98 = (LAST_BERRY_INDEX + 98),
    ITEM_TM99 = (LAST_BERRY_INDEX + 99),
    ITEM_TM100 = (LAST_BERRY_INDEX + 100),
    LAST_TECHNICAL_MACHINE_INDEX = ITEM_TM100,

    ITEM_HM01 = (LAST_TECHNICAL_MACHINE_INDEX + 1),
    ITEM_HM02 = (LAST_TECHNICAL_MACHINE_INDEX + 2),
    ITEM_HM03 = (LAST_TECHNICAL_MACHINE_INDEX + 3),
    ITEM_HM04 = (LAST_TECHNICAL_MACHINE_INDEX + 4),
    ITEM_HM05 = (LAST_TECHNICAL_MACHINE_INDEX + 5),
    ITEM_HM06 = (LAST_TECHNICAL_MACHINE_INDEX + 6),
    ITEM_HM07 = (LAST_TECHNICAL_MACHINE_INDEX + 7),
    ITEM_HM08 = (LAST_TECHNICAL_MACHINE_INDEX + 8),
    LAST_HIDDEN_MACHINE_INDEX = ITEM_HM08,


    /* Expands to:
     *   ITEM_TM_FOCUS_PUNCH = ITEM_TM01,
     *   ...
     *   ITEM_HM_CUT = ITM_HM01,
     *   ... */
    #define ENUM_TM(n, id) CAT(ITEM_TM_, id) = CAT(ITEM_TM, n),
    #define ENUM_HM(n, id) CAT(ITEM_HM_, id) = CAT(ITEM_HM, n),
    #define TO_TMHM_NUMS(a, ...) (__VA_ARGS__)
    RECURSIVELY(R_ZIP(ENUM_TM, TO_TMHM_NUMS NUMBERS_256, (FOREACH_TM(APPEND_COMMA))))
    RECURSIVELY(R_ZIP(ENUM_HM, TO_TMHM_NUMS NUMBERS_256, (FOREACH_HM(APPEND_COMMA))))
    #undef ENUM_TM
    #undef ENUM_HM
    #undef TO_TMHM_NUMS

    // Charms
    ITEM_OVAL_CHARM = (LAST_HIDDEN_MACHINE_INDEX + 1),
    ITEM_SHINY_CHARM = (LAST_HIDDEN_MACHINE_INDEX + 2),
    ITEM_CATCHING_CHARM = (LAST_HIDDEN_MACHINE_INDEX + 3),
    ITEM_EXP_CHARM = (LAST_HIDDEN_MACHINE_INDEX + 4),

    // Form-changing Key Items
    ITEM_ROTOM_CATALOG = (LAST_HIDDEN_MACHINE_INDEX + 5),
    ITEM_GRACIDEA = (LAST_HIDDEN_MACHINE_INDEX + 6),
    ITEM_REVEAL_GLASS = (LAST_HIDDEN_MACHINE_INDEX + 7),
    ITEM_DNA_SPLICERS = (LAST_HIDDEN_MACHINE_INDEX + 8),
    ITEM_ZYGARDE_CUBE = (LAST_HIDDEN_MACHINE_INDEX + 9),
    ITEM_PRISON_BOTTLE = (LAST_HIDDEN_MACHINE_INDEX + 10),
    ITEM_N_SOLARIZER = (LAST_HIDDEN_MACHINE_INDEX + 11),
    ITEM_N_LUNARIZER = (LAST_HIDDEN_MACHINE_INDEX + 12),
    ITEM_REINS_OF_UNITY = (LAST_HIDDEN_MACHINE_INDEX + 13),

    // Battle Mechanic Key Items
    ITEM_MEGA_RING = (LAST_HIDDEN_MACHINE_INDEX + 14),
    ITEM_Z_POWER_RING = (LAST_HIDDEN_MACHINE_INDEX + 15),
    ITEM_DYNAMAX_BAND = (LAST_HIDDEN_MACHINE_INDEX + 16),

    // Misc. Key Items
    ITEM_BICYCLE = (LAST_HIDDEN_MACHINE_INDEX + 17),
    ITEM_MACH_BIKE = (LAST_HIDDEN_MACHINE_INDEX + 18),
    ITEM_ACRO_BIKE = (LAST_HIDDEN_MACHINE_INDEX + 19),
    ITEM_OLD_ROD = (LAST_HIDDEN_MACHINE_INDEX + 20),
    ITEM_GOOD_ROD = (LAST_HIDDEN_MACHINE_INDEX + 21),
    ITEM_SUPER_ROD = (LAST_HIDDEN_MACHINE_INDEX + 22),
    ITEM_DOWSING_MACHINE = (LAST_HIDDEN_MACHINE_INDEX + 23),
    ITEM_ITEMFINDER = ITEM_DOWSING_MACHINE, // Pre-Gen IV name
    ITEM_DOWSING_MCHN = ITEM_DOWSING_MACHINE, // Gen IV-V name
    ITEM_TOWN_MAP = (LAST_HIDDEN_MACHINE_INDEX + 24),
    ITEM_VS_SEEKER = (LAST_HIDDEN_MACHINE_INDEX + 25),
    ITEM_TM_CASE = (LAST_HIDDEN_MACHINE_INDEX + 26),
    ITEM_BERRY_POUCH = (LAST_HIDDEN_MACHINE_INDEX + 27),
    ITEM_POKEMON_BOX_LINK = (LAST_HIDDEN_MACHINE_INDEX + 28),
    ITEM_POKEMON_BOX = ITEM_POKEMON_BOX_LINK, // Pre-Gen VIII name
    ITEM_COIN_CASE = (LAST_HIDDEN_MACHINE_INDEX + 29),
    ITEM_POWDER_JAR = (LAST_HIDDEN_MACHINE_INDEX + 30),
    ITEM_WAILMER_PAIL = (LAST_HIDDEN_MACHINE_INDEX + 31),
    ITEM_POKE_RADAR = (LAST_HIDDEN_MACHINE_INDEX + 32),
    ITEM_POKEBLOCK_CASE = (LAST_HIDDEN_MACHINE_INDEX + 33),
    ITEM_SOOT_SACK = (LAST_HIDDEN_MACHINE_INDEX + 34),
    ITEM_POKE_FLUTE = (LAST_HIDDEN_MACHINE_INDEX + 35),
    ITEM_FAME_CHECKER = (LAST_HIDDEN_MACHINE_INDEX + 36),
    ITEM_TEACHY_TV = (LAST_HIDDEN_MACHINE_INDEX + 37),

    // Story Key Items
    ITEM_SS_TICKET = (LAST_HIDDEN_MACHINE_INDEX + 38),
    ITEM_EON_TICKET = (LAST_HIDDEN_MACHINE_INDEX + 39),
    ITEM_MYSTIC_TICKET = (LAST_HIDDEN_MACHINE_INDEX + 40),
    ITEM_AURORA_TICKET = (LAST_HIDDEN_MACHINE_INDEX + 41),
    ITEM_OLD_SEA_MAP = (LAST_HIDDEN_MACHINE_INDEX + 42),
    ITEM_LETTER = (LAST_HIDDEN_MACHINE_INDEX + 43),
    ITEM_DEVON_PARTS = (LAST_HIDDEN_MACHINE_INDEX + 44),
    ITEM_DEVON_GOODS = ITEM_DEVON_PARTS, // Pre-Gen VI name
    ITEM_GO_GOGGLES = (LAST_HIDDEN_MACHINE_INDEX + 45),
    ITEM_DEVON_SCOPE = (LAST_HIDDEN_MACHINE_INDEX + 46),
    ITEM_BASEMENT_KEY = (LAST_HIDDEN_MACHINE_INDEX + 47),
    ITEM_SCANNER = (LAST_HIDDEN_MACHINE_INDEX + 48),
    ITEM_STORAGE_KEY = (LAST_HIDDEN_MACHINE_INDEX + 49),
    ITEM_KEY_TO_ROOM_1 = (LAST_HIDDEN_MACHINE_INDEX + 50),
    ITEM_RM_1_KEY = ITEM_KEY_TO_ROOM_1, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_2 = (LAST_HIDDEN_MACHINE_INDEX + 51),
    ITEM_RM_2_KEY = ITEM_KEY_TO_ROOM_2, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_4 = (LAST_HIDDEN_MACHINE_INDEX + 52),
    ITEM_RM_4_KEY = ITEM_KEY_TO_ROOM_4, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_6 = (LAST_HIDDEN_MACHINE_INDEX + 53),
    ITEM_RM_6_KEY = ITEM_KEY_TO_ROOM_6, // Pre-Gen VI name
    ITEM_METEORITE = (LAST_HIDDEN_MACHINE_INDEX + 54),
    ITEM_MAGMA_EMBLEM = (LAST_HIDDEN_MACHINE_INDEX + 55),
    ITEM_CONTEST_PASS = (LAST_HIDDEN_MACHINE_INDEX + 56),
    ITEM_PARCEL = (LAST_HIDDEN_MACHINE_INDEX + 57),
    ITEM_OAKS_PARCEL = ITEM_PARCEL, // Pre-Gen IV name
    ITEM_SECRET_KEY = (LAST_HIDDEN_MACHINE_INDEX + 58),
    ITEM_BIKE_VOUCHER = (LAST_HIDDEN_MACHINE_INDEX + 59),
    ITEM_GOLD_TEETH = (LAST_HIDDEN_MACHINE_INDEX + 60),
    ITEM_CARD_KEY = (LAST_HIDDEN_MACHINE_INDEX + 61),
    ITEM_LIFT_KEY = (LAST_HIDDEN_MACHINE_INDEX + 62),
    ITEM_SILPH_SCOPE = (LAST_HIDDEN_MACHINE_INDEX + 63),
    ITEM_TRI_PASS = (LAST_HIDDEN_MACHINE_INDEX + 64),
    ITEM_RAINBOW_PASS = (LAST_HIDDEN_MACHINE_INDEX + 65),
    ITEM_TEA = (LAST_HIDDEN_MACHINE_INDEX + 66),
    ITEM_RUBY = (LAST_HIDDEN_MACHINE_INDEX + 67),
    ITEM_SAPPHIRE = (LAST_HIDDEN_MACHINE_INDEX + 68),

    // GEN IX ITEMS
    ITEM_ABILITY_SHIELD = (LAST_HIDDEN_MACHINE_INDEX + 69),
    ITEM_CLEAR_AMULET = (LAST_HIDDEN_MACHINE_INDEX + 70),
    ITEM_PUNCHING_GLOVE = (LAST_HIDDEN_MACHINE_INDEX + 71),
    ITEM_COVERT_CLOAK = (LAST_HIDDEN_MACHINE_INDEX + 72),
    ITEM_LOADED_DICE = (LAST_HIDDEN_MACHINE_INDEX + 73),
    ITEM_AUSPICIOUS_ARMOR = (LAST_HIDDEN_MACHINE_INDEX + 74),
    ITEM_BOOSTER_ENERGY = (LAST_HIDDEN_MACHINE_INDEX + 75),
    ITEM_BIG_BAMBOO_SHOOT = (LAST_HIDDEN_MACHINE_INDEX + 76),
    ITEM_GIMMIGHOUL_COIN = (LAST_HIDDEN_MACHINE_INDEX + 77),
    ITEM_LEADERS_CREST = (LAST_HIDDEN_MACHINE_INDEX + 78),
    ITEM_MALICIOUS_ARMOR = (LAST_HIDDEN_MACHINE_INDEX + 79),
    ITEM_MIRROR_HERB = (LAST_HIDDEN_MACHINE_INDEX + 80),
    ITEM_SCROLL_OF_DARKNESS = (LAST_HIDDEN_MACHINE_INDEX + 81),
    ITEM_SCROLL_OF_WATERS = (LAST_HIDDEN_MACHINE_INDEX + 82),
    ITEM_TERA_ORB = (LAST_HIDDEN_MACHINE_INDEX + 83),
    ITEM_TINY_BAMBOO_SHOOT = (LAST_HIDDEN_MACHINE_INDEX + 84),

    ITEM_BUG_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 85),
    ITEM_DARK_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 86),
    ITEM_DRAGON_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 87),
    ITEM_ELECTRIC_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 88),
    ITEM_FAIRY_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 89),
    ITEM_FIGHTING_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 90),
    ITEM_FIRE_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 91),
    ITEM_FLYING_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 92),
    ITEM_GHOST_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 93),
    ITEM_GRASS_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 94),
    ITEM_GROUND_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 95),
    ITEM_ICE_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 96),
    ITEM_NORMAL_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 97),
    ITEM_POISON_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 98),
    ITEM_PSYCHIC_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 99),
    ITEM_ROCK_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 100),
    ITEM_STEEL_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 101),
    ITEM_WATER_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 102),

    ITEM_ADAMANT_CRYSTAL = (LAST_HIDDEN_MACHINE_INDEX + 103),
    ITEM_GRISEOUS_CORE = (LAST_HIDDEN_MACHINE_INDEX + 104),
    ITEM_LUSTROUS_GLOBE = (LAST_HIDDEN_MACHINE_INDEX + 105),

    ITEM_BLACK_AUGURITE = (LAST_HIDDEN_MACHINE_INDEX + 106),
    ITEM_LINKING_CORD = (LAST_HIDDEN_MACHINE_INDEX + 107),
    ITEM_PEAT_BLOCK = (LAST_HIDDEN_MACHINE_INDEX + 108),
    ITEM_BERSERK_GENE = (LAST_HIDDEN_MACHINE_INDEX + 109),

    ITEM_FAIRY_FEATHER = (LAST_HIDDEN_MACHINE_INDEX + 110),
    ITEM_SYRUPY_APPLE = (LAST_HIDDEN_MACHINE_INDEX + 111),
    ITEM_UNREMARKABLE_TEACUP = (LAST_HIDDEN_MACHINE_INDEX + 112),
    ITEM_MASTERPIECE_TEACUP = (LAST_HIDDEN_MACHINE_INDEX + 113),
    ITEM_CORNERSTONE_MASK = (LAST_HIDDEN_MACHINE_INDEX + 114),
    ITEM_WELLSPRING_MASK = (LAST_HIDDEN_MACHINE_INDEX + 115),
    ITEM_HEARTHFLAME_MASK = (LAST_HIDDEN_MACHINE_INDEX + 116),
    ITEM_HEALTH_MOCHI = (LAST_HIDDEN_MACHINE_INDEX + 117),
    ITEM_MUSCLE_MOCHI = (LAST_HIDDEN_MACHINE_INDEX + 118),
    ITEM_RESIST_MOCHI = (LAST_HIDDEN_MACHINE_INDEX + 119),
    ITEM_GENIUS_MOCHI = (LAST_HIDDEN_MACHINE_INDEX + 120),
    ITEM_CLEVER_MOCHI = (LAST_HIDDEN_MACHINE_INDEX + 121),
    ITEM_SWIFT_MOCHI = (LAST_HIDDEN_MACHINE_INDEX + 122),
    ITEM_FRESH_START_MOCHI = (LAST_HIDDEN_MACHINE_INDEX + 123),
    ITEM_GLIMMERING_CHARM = (LAST_HIDDEN_MACHINE_INDEX + 124),
    ITEM_METAL_ALLOY = (LAST_HIDDEN_MACHINE_INDEX + 125),
    ITEM_STELLAR_TERA_SHARD = (LAST_HIDDEN_MACHINE_INDEX + 126),

    ITEM_JUBILIFE_MUFFIN = (LAST_HIDDEN_MACHINE_INDEX + 127),
    ITEM_REMEDY = (LAST_HIDDEN_MACHINE_INDEX + 128),
    ITEM_FINE_REMEDY = (LAST_HIDDEN_MACHINE_INDEX + 129),
    ITEM_SUPERB_REMEDY = (LAST_HIDDEN_MACHINE_INDEX + 130),
    ITEM_AUX_EVASION = (LAST_HIDDEN_MACHINE_INDEX + 131),
    ITEM_AUX_GUARD = (LAST_HIDDEN_MACHINE_INDEX + 132),
    ITEM_AUX_POWER = (LAST_HIDDEN_MACHINE_INDEX + 133),
    ITEM_AUX_POWERGUARD = (LAST_HIDDEN_MACHINE_INDEX + 134),
    ITEM_CHOICE_DUMPLING = (LAST_HIDDEN_MACHINE_INDEX + 135),
    ITEM_SWAP_SNACK = (LAST_HIDDEN_MACHINE_INDEX + 136),
    ITEM_TWICE_SPICED_RADISH = (LAST_HIDDEN_MACHINE_INDEX + 137),
    ITEM_POKESHI_DOLL = (LAST_HIDDEN_MACHINE_INDEX + 138),

    ITEM_STRANGE_BALL = (LAST_HIDDEN_MACHINE_INDEX + 139),

    // Legends Z-A Mega Stones
    ITEM_CLEFABLITE = (LAST_HIDDEN_MACHINE_INDEX + 140),
    ITEM_VICTREEBELITE = (LAST_HIDDEN_MACHINE_INDEX + 141),
    ITEM_STARMINITE = (LAST_HIDDEN_MACHINE_INDEX + 142),
    ITEM_DRAGONINITE = (LAST_HIDDEN_MACHINE_INDEX + 143),
    ITEM_MEGANIUMITE = (LAST_HIDDEN_MACHINE_INDEX + 144),
    ITEM_FERALIGITE = (LAST_HIDDEN_MACHINE_INDEX + 145),
    ITEM_SKARMORITE = (LAST_HIDDEN_MACHINE_INDEX + 146),
    ITEM_FROSLASSITE = (LAST_HIDDEN_MACHINE_INDEX + 147),
    ITEM_EMBOARITE = (LAST_HIDDEN_MACHINE_INDEX + 148),
    ITEM_EXCADRITE = (LAST_HIDDEN_MACHINE_INDEX + 149),
    ITEM_SCOLIPITE = (LAST_HIDDEN_MACHINE_INDEX + 150),
    ITEM_SCRAFTINITE = (LAST_HIDDEN_MACHINE_INDEX + 151),
    ITEM_EELEKTROSSITE = (LAST_HIDDEN_MACHINE_INDEX + 152),
    ITEM_CHANDELURITE = (LAST_HIDDEN_MACHINE_INDEX + 153),
    ITEM_CHESNAUGHTITE = (LAST_HIDDEN_MACHINE_INDEX + 154),
    ITEM_DELPHOXITE = (LAST_HIDDEN_MACHINE_INDEX + 155),
    ITEM_GRENINJITE = (LAST_HIDDEN_MACHINE_INDEX + 156),
    ITEM_PYROARITE = (LAST_HIDDEN_MACHINE_INDEX + 157),
    ITEM_FLOETTITE = (LAST_HIDDEN_MACHINE_INDEX + 158),
    ITEM_MALAMARITE = (LAST_HIDDEN_MACHINE_INDEX + 159),
    ITEM_BARBARACITE = (LAST_HIDDEN_MACHINE_INDEX + 160),
    ITEM_DRAGALGITE = (LAST_HIDDEN_MACHINE_INDEX + 161),
    ITEM_HAWLUCHANITE = (LAST_HIDDEN_MACHINE_INDEX + 162),
    ITEM_ZYGARDITE = (LAST_HIDDEN_MACHINE_INDEX + 163),
    ITEM_DRAMPANITE = (LAST_HIDDEN_MACHINE_INDEX + 164),
    ITEM_FALINKSITE = (LAST_HIDDEN_MACHINE_INDEX + 165),

    // Legends Z-A: Mega Dimension DLC Mega Stones
    ITEM_HEATRANITE = (LAST_HIDDEN_MACHINE_INDEX + 166),
    ITEM_DARKRANITE = (LAST_HIDDEN_MACHINE_INDEX + 167),
    ITEM_ZERAORITE = (LAST_HIDDEN_MACHINE_INDEX + 168),
    ITEM_RAICHUNITE_X = (LAST_HIDDEN_MACHINE_INDEX + 169),
    ITEM_RAICHUNITE_Y = (LAST_HIDDEN_MACHINE_INDEX + 170),
    ITEM_CHIMECHITE = (LAST_HIDDEN_MACHINE_INDEX + 171),
    ITEM_ABSOLITE_Z = (LAST_HIDDEN_MACHINE_INDEX + 172),
    ITEM_STARAPTITE = (LAST_HIDDEN_MACHINE_INDEX + 173),
    ITEM_GARCHOMPITE_Z = (LAST_HIDDEN_MACHINE_INDEX + 174),
    ITEM_LUCARIONITE_Z = (LAST_HIDDEN_MACHINE_INDEX + 175),
    ITEM_GOLURKITE = (LAST_HIDDEN_MACHINE_INDEX + 176),
    ITEM_MEOWSTICITE = (LAST_HIDDEN_MACHINE_INDEX + 177),
    ITEM_CRABOMINITE = (LAST_HIDDEN_MACHINE_INDEX + 178),
    ITEM_GOLISOPITE = (LAST_HIDDEN_MACHINE_INDEX + 179),
    ITEM_MAGEARNITE = (LAST_HIDDEN_MACHINE_INDEX + 180),
    ITEM_SCOVILLAINITE = (LAST_HIDDEN_MACHINE_INDEX + 181),
    ITEM_BAXCALIBRITE = (LAST_HIDDEN_MACHINE_INDEX + 182),
    ITEM_TATSUGIRINITE = (LAST_HIDDEN_MACHINE_INDEX + 183),
    ITEM_GLIMMORANITE = (LAST_HIDDEN_MACHINE_INDEX + 184),

    ITEMS_COUNT,
    ITEM_FIELD_ARROW = ITEMS_COUNT,
};

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1
#define STANDARD_BIKE 2

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
enum ItemType
{
    ITEM_USE_MAIL,
    ITEM_USE_PARTY_MENU,
    ITEM_USE_FIELD,
    ITEM_USE_PBLOCK_CASE,
    ITEM_USE_BAG_MENU, // No exit callback, stays in bag menu
    ITEM_USE_PARTY_MENU_MOVES,
    ITEM_USE_BATTLER, // Auto-select in Singles but lets you choose from party menu in Doubles
};

// Item battle script IDs (need to be non-zero)
enum EffectItem
{
    EFFECT_ITEM_ENIGMA_BERRY_EREADER = 1, // dummy constant
    EFFECT_ITEM_RESTORE_HP = 1, // needs to be non-zero
    EFFECT_ITEM_CURE_STATUS,
    EFFECT_ITEM_HEAL_AND_CURE_STATUS,
    EFFECT_ITEM_INCREASE_STAT,
    EFFECT_ITEM_SET_MIST,
    EFFECT_ITEM_SET_FOCUS_ENERGY,
    EFFECT_ITEM_ESCAPE,
    EFFECT_ITEM_THROW_BALL,
    EFFECT_ITEM_REVIVE,
    EFFECT_ITEM_RESTORE_PP,
    EFFECT_ITEM_INCREASE_ALL_STATS,
    EFFECT_ITEM_USE_POKE_FLUTE,
};

#endif  // GUARD_CONSTANTS_ITEMS_H
